# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Recipes by J. Scott Johnson
email: fuzzygroup [at] gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal collection of gluten free recipes.  I used to use KeyIngredient but as that has become progressively worse 
  I moved everything to my local box and published it on github using this tutorial: <a href='https://24ways.org/2013/get-started-with-github-pages/'>Github Pages</a>.
baseurl: /recipes # the subpath of your site, e.g. /blog
url: "https://fuzzyblog.io" # the base hostname & protocol for your site
twitter_username: fuzzygroup
github_username:  fuzzygroup

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-lunr-js-search
  - jekyll-sitemap
  
#
# gallery:
#   hidden: true
#   dir: photos               # Path to the gallery
#   symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
#   title: "Photos"           # Title for gallery index page
#   #title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
#   sort_field: "date_time"   # How to sort galleries on the index page.
#                             # Possible values are: title, date_time, best_image
#   thumbnail_size:
#     x: 400                  # max width of thumbnails (in pixels)
#     y: 400                  # max height of thumbnails (in pixels)
#   # The following options are for individual galleries.
#   galleries:
#     # chile_trip:
#     #   best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
#     # japan_trip:
#     #   best_image: IMG_0690.JPG
#     #   name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
#     # awesome_stuff:
#     #   best_image: snaileo_gonzales.jpg
#     #   sort_reverse: true    # Reverse sort images in gallery.
#     secret_stuff:
#       hidden: true          # Don't show this gallery on the index page. People must guess the URL.
